### ISSUE TITLE
Flutter 3.0 changes

### ISSUE THREAD

**Issue by zawadZwd** [Dev-hwang/flutter_foreground_task#78]
Hello
After releasing new flutter version, the plugin do not work because of this error: 

```dart
.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.7.2/lib/ui/will_start_foreground_task.dart:95:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Flutter/packages/flutter/lib/src/widgets/binding.dart').
 WidgetsBinding.instance?.addObserver(this);
```

**Comment by zawadZwd** [comment]
Also there is a warning which I believe there wasn't before:

```dart
.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.7.2/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (329, 18): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.7.2/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (347, 4): 'error' overrides nothing
```

**Comment by blopker** [comment]
I can confirm our builds are failing on Flutter 3 because of this. Anything we can do to help?

**Comment by Dev-hwang** [comment]
Try upgrading to version 3.7.3

```yaml
dependencies:
  flutter_foreground_task: ^3.7.3
```

**Comment by blopker** [comment]
Works for us! Thanks for the quick turnaround. 👍

**Comment by Faiizii** [comment]
I am using Android 12, and `flutter_foreground_task: ^3.7.3` Yesterday, I have integrated your lib and it was showing notification in notification panel. after upgrading to 3.7.3 notification is not showing whereas `OnEvent` of my `TaskHandler` is calling with regular interval. I have flutter 3 version.
